alias: COMI-Derrame-de-Petroleo

generate-output: true
solution: solution/solution.cpp
timeout: 9
admin-groups: [workshop-2017]
params:
  title: Derrame de Petroleo
  source: Curso OMI (ORAC)

  visibility: 1

  # valid options: all, karel
  languages: all

  time_limit: 3000
  memory_limit: 65536
  output_limit: 8009984
  stack_limit: 2147483647

  overall_wall_time_limit: 60000

  # valid options: token-caseless, token-numeric, token-numeric, custom, literal
  validator: token-caseless
  validator_time_limit: 1000
  extra_wall_time: 0

  email_clarifications: 0
