language: python
python:
- '3.5'
install:
- pip install pipenv
- pushd omegaUp-deploy
- pipenv install
script:
- pipenv run python3 deploy.py "../comida fria"
env:
  global:
  - secure: r4dk13NNX6OcnDtXDCAd5gbEVYJUubfPWtWWK+ZbMAckICJ2CKmfw3XTnBUj6F9BWpeLt9FSpQGkF54vqnRfR4XSrQUS47BhHy37ej03y0O6AMh5WGdFqhQA52w/4b+rxfhLrn/V0QY4HHhT+pifXcXdFN2TMir6lfF1mkyvdS90fy1QCT4oXHh2JE4dh1hNOXIGUXlkdvHiaJVoViGBNOoMH4GwYV/mkBdCZcAAhW8JE15Er89Kc5fYZ3aCtOY0QdzrX1BWE5fwuQe6DyrNpa2lbw5psBmSgH45o84JK8xIZRQnAzdIAo00L4mAP4YuR4Y5a5H+N37+fYBtv6wlJe8paD6aMU9sMr6TM1qWh9EwRfOhNhgj9WFQl/dU5mQrjhlrJeINfKNPbAeKYvhHyRxaC3g3o7zdlXY/qckUA40GubpN/TAoNPPFiO0KgskpYV0k5JDSJ1i7mwotGJys3FVPDoO92mE9M6Qc19BsWBTzz/ZPlHVDeKrC/nkCrL8cMSSWC1Lj5tE2hZBoqnZyvfKXZbJhRttgcz46VL2+AFNxgGBXZQIavlYQnisayNsgEGl4BZYu57XvcO/dSmeBkOXo38m/oZ68lkxp9ZPHvoT3NbA+25vJVT0wB/kGbRFzJAQceIF4TFaiD9eKpDrg8SLUPEgYy5xdAEbyiUBqQUI=
  - secure: QBF5fzsDqPnvRfLi+rzyHGOkPilxXSEvRAGDVqlcT2eHD0QAvSpiEOmNnpOWtkD9LY6EB0pdJByy44uLEmgShAcBnMja8KcLxNhGOjcW29Z9t+W7OTZMbU1krifPHBEy73NQZVuZkmRq9Tp92LcssdmFv4jM9iUD6XOW/kO0niBK36K7w+LiyVx8d79xlqTvBVWjwZMAMWL8A5uitLL9jH3RjZIzSPtvwj4wR3ZATC4e2oG01Q0BN9Sm9WdLMCwzORtn9uWrCkVRcxs1EioXqc8bVUdGn7DheayETzl358/TsTx0/9pk1Lvprv9L6AH5CKPA8pqeyfQ6wzJh5Q/7xnIsEegJbyaNl0wtKvBHsJ/nE8ZZ593uaMn/Tnjve6ZEmmlni8LLivGu+JKzmykkvp0ocBM+WwfHYGtVHCS2hCsdOdIKp2I+k5BZnfrLs8MGogVtePwG3HIs37HUHREsdAp0n0yA7BXbyjvKE/2J0yUyJ88Bdkl5T4A+Un9LDbbcN97zmNg/ASLuyFh3SobZb6oJL54DsplOMBJTCrb57SWnO5bAdq828Z3jaBVhW1gUgMhpFexcd5lOU0Xu//bvNy3LgW0sAg29Bt+bFSwneL7pgg2OhbWET7p5OqR2zMhixd6MNoh3vplZ6OyXB6glfF575rjz2QdptFHBIotbEn8=
