alias: COMI-Palindromos

generate-output: true
solution: solutions/100_B.cpp
timeout: 0.5

params:
  title: Palindromos
  source: Curso OMI (Orac)

  visibility: 0

  languages: all

  time_limit: 1000
  memory_limit: 32768
  output_limit: 16384
  stack_limit: 10485760

  overall_wall_time_limit: 60000

  validator: token-caseless
  validator_time_limit: 1000
  extra_wall_time: 0

  email_clarifications: 0
