alias: COMI-Derrame-de-Petroleo

generate-output: true
solution: solution/solucion2.cpp
timeout: 1.5

params:
  title: Derrame de Petroleo
  source: Curso OMI (ORAC)

  visibility: 1

  # valid options: all, karel
  languages: all

  time_limit: 2000
  memory_limit: 65536
  output_limit: 16384
  stack_limit: 10485760

  overall_wall_time_limit: 60000

  # valid options: token-caseless, token-numeric, token-numeric, custom, literal
  validator: token-caseless
  validator_time_limit: 1000
  extra_wall_time: 0

  email_clarifications: 0
